# Project

In [2]:
import numpy as np
#import pandas as pd
#from sklearn import svm
#from sklearn.model_selection import train_test_split
#from matplotlib import pyplot as plt

labels_file = "../Model/NeuralNetworkFiles/" + "parts_03_truth.csv"
labels = np.loadtxt(labels_file, delimiter=',')
print(labels[:5])

#table = pd.read_csv('taxi+_zone_lookup.csv')
#taxi = pd.read_csv('green_tripdata_2019-01.csv')

[[0.000e+00 3.395e+03 1.000e+00]
 [1.000e+00 3.396e+03 1.000e+00]
 [2.000e+00 3.397e+03 1.000e+00]
 [3.000e+00 3.398e+03 1.000e+00]
 [4.000e+00 3.399e+03 1.000e+00]]


In [0]:
train, test = train_test_split(df, test_size=0.2)
train, val = train_test_split(train, test_size=0.2)

train_X = train[['tip', 'PULocationID', 'PUNeighborhood', 'DOLocationID', 'DONeighborhood']]
train_y = train['payment_type']
val_X = val[['tip', 'PULocationID', 'PUNeighborhood', 'DOLocationID', 'DONeighborhood']]
val_y = val['payment_type']
test_X = test[['tip', 'PULocationID', 'PUNeighborhood', 'DOLocationID', 'DONeighborhood']]
test_y = test['payment_type']

train_X.head()

tip  PULocationID  PUNeighborhood  DOLocationID  DONeighborhood
21766  False            78               0            78               0
22905   True            75               3           166               3
24007  False            74               3            41               3
23408   True            24               3           142               3
23545  False           116               3           116               3

# Model fitting

In [0]:
rbf_svm = svm.SVC(C=1000, gamma=1/100000, kernel='rbf')
rbf_svm.fit(train_X, train_y)
print("Train accuracy: {}".format(rbf_svm.score(train_X, train_y)))
print("Validation accuracy: {}".format(rbf_svm.score(val_X, val_y)))

Train accuracy: 0.785546875
Validation accuracy: 0.8015625


Final test accuracy confirms, that the model is right about 80% of the time, not bad! I suppose this confirms the claim, that there really is a correlation between the location of the passanger, his willingness to pay the tip and the type of payment he has used.

In [0]:
print("Test accuracy: {}".format(rbf_svm.score(test_X, test_y)))

Test accuracy: 0.79125




---
